/**
 * Users DataService
 * Uses embedded, hard-coded data model; acts asynchronously to simulate
 * remote data service call(s).
 *
 * @returns {{loadAll: Function}}
 * @constructor
 */
function DeviceDataService($q) {
  var devices = [
    {
      name: 'Light Bulb',
      avatar: 'light-bulb',
      content: 'An incandescent light bulb, incandescent lamp or incandescent light globe is an electric light with a wire filament heated to such a high temperature that it glows with visible light (incandescence). The filament, heated by passing an electric current through it, is protected from oxidation with a glass or fused quartz bulb that is filled with inert gas or evacuated. In a halogen lamp, filament evaporation is slowed by a chemical process that redeposits metal vapor onto the filament, extending its life. The light bulb is supplied with electric current by feed-through terminals or wires embedded in the glass. Most bulbs are used in a socket which provides mechanical support and electrical connections.\n' +
      '\n' +
      'Incandescent bulbs are manufactured in a wide range of sizes, light output, and voltage ratings, from 1.5 volts to about 300 volts. They require no external regulating equipment, have low manufacturing costs, and work equally well on either alternating current or direct current. As a result, the incandescent lamp is widely used in household and commercial lighting, for portable lighting such as table lamps, car headlamps, and flashlights, and for decorative and advertising lighting.\n' +
      '\n' +
      'Incandescent bulbs are much less efficient than most other types of electric lighting; incandescent bulbs convert less than 5% of the energy they use into visible light,[1] with standard light bulbs averaging about 2.2%.[2] The remaining energy is converted into heat. The luminous efficacy of a typical incandescent bulb is 16 lumens per watt, compared with 60 lm/W for a compact fluorescent bulb or 150 lm/W for some white LED lamps.[3] Some applications of the incandescent bulb (such as heat lamps) deliberately use the heat generated by the filament. Such applications include incubators, brooding boxes for poultry,[4] heat lights for reptile tanks,[5] infrared heating for industrial heating and drying processes, lava lamps, and the Easy-Bake Oven toy. Incandescent bulbs typically have short lifetimes compared with other types of lighting; around 1,000 hours for home light bulbs versus typically 10,000 hours for compact fluorescents and 30,000 hours for lighting LEDs.'
    },
    {
      name: 'Heating',
      avatar: 'machine',
      content: 'A central heating system provides warmth to the whole interior of a building (or portion of a building) from one point to multiple rooms. When combined with other systems in order to control the building climate, the whole system may be an HVAC (heating, ventilation and air conditioning) system.'
    }
  ];

  // Promise-based API
  return {
    loadAllDevices: function() {
      // Simulate async nature of real remote calls
      return $q.when(devices);
    }
  };
}

export default ['$q', DeviceDataService];

